import QtQuick
import QtQuick.Effects
import "components"

// lucid's lock screen, wearing sddm's auth instead of pam. the composition is
// the shell's LockSurface: the day on the left, the one thing to answer on the
// right, and the ways out underneath
Item {
    id: surface

    // sddm loads this once per screen. only one of them asks for a password
    readonly property bool primary: (typeof primaryScreen === "undefined") ? true : primaryScreen
    // the arrival driver, linear in time so each block can ease its own slice
    property real t: 0
    // 1 while the greeter is here, 0 once the password has been taken
    property real out: 1
    // 0 glance, 1 focus. the day steps back so the field can step forward
    property real focusK: Lock.focused ? 1 : 0
    // while the field has the screen, everything that steps back also stops
    // taking clicks and hover. a click out there only buys the focus back
    readonly property bool glanceLive: !Lock.focused
    readonly property real e: surface.ease(surface.t)
    readonly property int pad: Math.round(Math.max(36, Math.min(76, surface.height * 0.062)))
    readonly property int rightWidth: Math.round(Math.max(340, Math.min(440, surface.width * 0.25)))

    width: 1920
    height: 1080

    // a long tail, so a block lands rather than stops
    function ease(x) {
        var c = Math.max(0, Math.min(1, x));
        return 1 - Math.pow(1 - c, 5);
    }

    // a block's own progress: nothing until its turn, then a full ease of its own
    function rv(delay) {
        return surface.ease((surface.t - delay) / Math.max(0.05, 1 - delay));
    }

    Behavior on focusK {
        NumberAnimation {
            duration: Theme.ms(520)
            easing.type: Easing.Bezier
            easing.bezierCurve: Theme.easeEmphasizedDecel
        }

    }

    NumberAnimation {
        id: enterAnim

        target: surface
        property: "t"
        to: 1
        duration: Theme.ms(900)
    }

    // the greeter leans forward and dissolves as the session takes over
    ParallelAnimation {
        id: exitAnim

        NumberAnimation {
            target: surface
            property: "out"
            to: 0
            duration: Theme.ms(300)
            easing.type: Easing.Bezier
            easing.bezierCurve: Theme.easeEmphasizedAccel
        }

    }

    Connections {
        function onPhaseChanged() {
            if (Lock.granted)
                exitAnim.restart();

        }

        target: Lock
    }

    // the models, read by role name so no role number has to be guessed
    Instantiator {
        model: userModel

        delegate: QtObject {
            required property string name
            required property string realName
            required property string icon
            required property bool needsPassword
        }

        onObjectAdded: surface.syncUsers()
        onObjectRemoved: surface.syncUsers()

        id: users
    }

    Instantiator {
        id: sessions

        model: sessionModel

        delegate: QtObject {
            required property string name
        }

        onObjectAdded: surface.syncSessions()
        onObjectRemoved: surface.syncSessions()
    }

    function syncUsers() {
        var out = [];
        for (var i = 0; i < users.count; i++) {
            var o = users.objectAt(i);
            if (o)
                out.push({
                    "name": o.name,
                    "realName": o.realName,
                    "icon": o.icon,
                    "needsPassword": o.needsPassword
                });

        }
        Lock.accounts = out;
    }

    function syncSessions() {
        var out = [];
        for (var i = 0; i < sessions.count; i++) {
            var o = sessions.objectAt(i);
            if (o)
                out.push(o.name);

        }
        Lock.sessions = out;
    }

    Component.onCompleted: {
        surface.syncUsers();
        surface.syncSessions();
        // sddm remembers who logged in last, and into what
        for (var i = 0; i < Lock.accounts.length; i++) {
            if (Lock.accounts[i].name === userModel.lastUser) {
                Lock.index = i;
                break;
            }
        }
        if (sessionModel.lastIndex >= 0 && sessionModel.lastIndex < Lock.sessions.length)
            Lock.sessionIndex = sessionModel.lastIndex;

        surface.t = 0;
        surface.out = 1;
        enterAnim.start();
        if (surface.primary)
            Qt.callLater(auth.focusInput);

    }

    // ── backdrop ───────────────────────────────────────────────────────────
    // the scale has to live on a child: MultiEffect renders its source without
    // the source item's own transform, so a scale on the Image itself is lost
    Item {
        id: paperBox

        anchors.fill: parent

        // background.jpg is generated by sync-sddm.sh and deliberately not in
        // the repo, so a fresh clone has none until the first theme apply.
        // this keeps that case looking like a flat lucid surface
        Rectangle {
            anchors.fill: parent
            color: Theme.bgOpaque
        }

        Image {
            anchors.fill: parent
            source: config.background
            fillMode: Image.PreserveAspectCrop
            asynchronous: true
            cache: true
            scale: 1.07 - 0.07 * surface.e + surface.focusK * 0.02 + (1 - surface.out) * 0.06
        }

    }

    // the lock blurs the wallpaper live; a greeter should not be running a
    // 64px blur over 1080p on a cold gpu at boot, so sync-sddm.sh bakes the
    // resting blur into background.jpg and this only adds the focus deepening
    MultiEffect {
        anchors.fill: parent
        source: paperBox
        autoPaddingEnabled: false
        blurEnabled: true
        blurMax: 64
        blur: surface.e * surface.out * surface.focusK * 0.32
        visible: surface.focusK > 0.01
    }

    Rectangle {
        anchors.fill: parent
        opacity: surface.e * surface.out * (0.34 + surface.focusK * 0.14)

        gradient: Gradient {
            GradientStop {
                position: 0
                color: Theme.alpha(Theme.cScrim, 0.75)
            }

            GradientStop {
                position: 0.45
                color: Theme.alpha(Theme.cScrim, 0.95)
            }

            GradientStop {
                position: 1
                color: Theme.cScrim
            }

        }

    }

    // material you's whole point: the wallpaper's own colour laid back over it
    Rectangle {
        anchors.fill: parent
        color: Theme.accent
        opacity: surface.e * surface.out * 0.07
    }

    // everything drawn on top leaves together
    Item {
        id: stage

        anchors.fill: parent
        opacity: surface.out
        scale: 1 + (1 - surface.out) * 0.05

        // a click anywhere off the card puts the greeter back to its resting
        // face and forgets whatever was half-typed
        MouseArea {
            anchors.fill: parent
            onClicked: {
                auth.discard();
                Lock.disengage();
            }
        }

        // ── glance chips, top right ────────────────────────────────────────
        Chips {
            id: chips

            anchors.right: parent.right
            anchors.rightMargin: surface.pad
            anchors.top: parent.top
            anchors.topMargin: surface.pad
            visible: surface.primary
            opacity: surface.rv(0.06) * (1 - surface.focusK * 0.6)
            enabled: surface.glanceLive

            transform: Translate {
                y: (1 - surface.rv(0.06)) * -24
            }

        }

        // ── the clock, left ────────────────────────────────────────────────
        Clock {
            anchors.left: parent.left
            anchors.leftMargin: surface.pad + 14
            anchors.verticalCenter: parent.verticalCenter
            unit: surface.primary ? Math.round(Math.min(178, surface.height * 0.155)) : Math.round(Math.min(220, surface.height * 0.19))
            visible: surface.primary
            opacity: surface.rv(0.1)

            transform: Translate {
                x: (1 - surface.rv(0.1)) * -30
                y: (1 - surface.rv(0.1)) * 22
            }

        }

        // ── the column that asks, right ────────────────────────────────────
        Item {
            id: rightCol

            anchors.right: parent.right
            anchors.rightMargin: surface.pad
            anchors.top: chips.bottom
            anchors.topMargin: 26
            anchors.bottom: parent.bottom
            anchors.bottomMargin: surface.pad + 64
            width: surface.rightWidth
            visible: surface.primary

            AuthCard {
                id: auth

                width: parent.width
                anchors.verticalCenter: parent.verticalCenter
                opacity: surface.rv(0.16)
                transformOrigin: Item.Right
                scale: 0.96 + 0.04 * surface.rv(0.16)

                transform: Translate {
                    x: (1 - surface.rv(0.16)) * 44
                }

            }

        }

        // ── the ways out, bottom left ──────────────────────────────────────
        PowerBar {
            anchors.left: parent.left
            anchors.leftMargin: surface.pad + 14
            anchors.bottom: parent.bottom
            anchors.bottomMargin: surface.pad
            visible: surface.primary
            opacity: surface.rv(0.5) * (1 - surface.focusK * 0.6)
            enabled: surface.glanceLive

            transform: Translate {
                y: (1 - surface.rv(0.5)) * 30
            }

        }

        // ── every other screen: the time, and nothing to type into ─────────
        Column {
            anchors.centerIn: parent
            spacing: 10
            visible: !surface.primary
            opacity: surface.rv(0.08)

            transform: Translate {
                y: (1 - surface.rv(0.08)) * 24
            }

            Clock {
                anchors.horizontalCenter: parent.horizontalCenter
                unit: Math.round(Math.min(200, surface.height * 0.17))
            }

            Row {
                anchors.horizontalCenter: parent.horizontalCenter
                spacing: 8
                topPadding: 18

                Glyph {
                    anchors.verticalCenter: parent.verticalCenter
                    name: "lock"
                    size: 17
                    color: Theme.subtextDim
                }

                Text {
                    anchors.verticalCenter: parent.verticalCenter
                    text: sddm.hostName
                    color: Theme.subtextDim
                    font.family: Theme.fontFamily
                    font.pixelSize: Theme.fontBodyMd
                }

            }

        }

    }

}
