[General]
# written by sync-sddm.sh from the running shell. edits are overwritten.
background=background.jpg

isLight=false
accent=#ffb1c4
accentHover=#ffc9d6
fgAccent=#5e1130
accentMuted=#e6bcc6
accentContainer=#762744
fgAccentContainer=#ffd9e1
bgOpaque=#0f080a
bgHigh=#3a3032
text=#efdfe1
subtext=#d6c2c6
subtextDim=#aa9a9d
outline=#524347
outlineStrong=#9e8c90
error=#ffb4ab
fgError=#690005
errorHover=#ffcbc6
success=#36e27e
fgSuccess=#06381b
warning=#eec13a
scrim=#000000
fontFamily=Google Sans
fontScale=0.9
motionScale=1.125
clock24h=false
